### ISSUE TITLE
I have 2 questions

### ISSUE THREAD

**Issue by Yomamaeatstoes** [killerprojecte/Folia#12]
Where is the discord

is the plan to fork this to folia and when?

**Comment by killerprojecte** [comment]
First, There is no discord channel for this project, and there are no plans for it in the future.
Secondly, this branch is third-party and will not be merged into folia at any time.

**Comment by Yomamaeatstoes** [comment]
Awwwww. Thanks for the clarity. I love what you guys have been doing here, so I was curious.

**Comment by killerprojecte** [comment]
issue has been resolved
