### ISSUE TITLE
RAM Unknown exception

### ISSUE THREAD

**Issue by 347180440** [killerprojecte/Folia#13]
### Expected behavior

This issue is a memory leak, and I'm not sure about the exact cause. I've uninstalled all plugins and tested it for a night with 5 players idling, and the memory usage slowly increased. Within a day, it reached the maximum RAM limit I set at 64GB. On average, there are around 10 players on the server, and once the memory overflows, the CPU maxes out at 100%, causing the server to freeze.

My suspicion is that it might be related to the server's world generation or calculations consuming a lot of RAM, but it's consuming it rapidly, and there's no garbage collection happening within a day. To rule out plugin-related issues, I've even uninstalled all plugins, but the problem persists. I've switched back to Purpur, and after a day, it hasn't exceeded 5GB of RAM usage, with no memory garbage. I'll have some free time to test other server cores to see if the issue remains.

If you've encountered a similar problem, please share your experiences. Let's work together to identify the root cause.

### Observed/Actual behavior

![1](https://github.com/killerprojecte/Folia/assets/107541071/16d0f7ef-4639-4280-b202-4b62f301d197)
![2](https://github.com/killerprojecte/Folia/assets/107541071/aa56c479-e538-4277-80c2-14c3b8380ba0)

### Steps/models to reproduce

This issue has been present for several months, and it was challenging to detect. I hadn't been paying close attention until now when I discovered that the cause is a memory leak.

### Plugin and Datapack List

Testing without any plugins.

### Folia version

[05:29:24 INFO]: This server is running DirtyFolia version git-DirtyFolia-"8d7dee3" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 8d7dee3 on ver/1.20)
You are running the latest version
Previous version: git-Purpur-2001 (MC: 1.20.1)

**Comment by MrHua269** [comment]
https://github.com/Era4FunMC/DirtyMolia/ 来试试这个吗()

**Comment by killerprojecte** [comment]
I will investigate the cause and if it is caused by Dirty Folia I will fix it as a priority.
If you can provide memory analysis data similar to that generated by JProfiler, it will save a lot of time for my investigation.

**Comment by killerprojecte** [comment]
> https://github.com/Era4FunMC/DirtyMolia/ 来试试这个吗()

I think your approach to the project will be better than mine, but there are still many important features missing. DirtyFolia is more like a milestone, I have given so much to Folia, maybe it is time to leave it to the community to continue completing my original intention.  This project has been maintained for 6 months and is as old as Folia.

**Maybe it’s not a good idea to win over users in other people’s projects**

**Comment by 347180440** [comment]
JProfiler analyzes the data. I'll need to research how to use it to obtain the memory analysis data you require.

**Comment by killerprojecte** [comment]
> JProfiler analyzes the data. I'll need to research how to use it to obtain the memory analysis data you require.

I only need to get which Java classes occupy more memory, but general analysis tools can only get the occupied object classes rather than the classes that store objects.  As far as I know, JProfiler can obtain similar data.

**Comment by 347180440** [comment]
> https://github.com/Era4FunMC/DirtyMolia/ 来试试这个吗（）
OK 明晚在试试 我先等一份-JProfiler 分析报告

**Comment by 347180440** [comment]
![image](https://github.com/killerprojecte/Folia/assets/107541071/c1ad3037-ba53-4574-9f3e-40384b518fe1)
Current two hour data

**Comment by MrHua269** [comment]
> > https://github.com/Era4FunMC/DirtyMolia/ 来试试这个吗()
> 
> I think your approach to the project will be better than mine, but there are still many important features missing. DirtyFolia is more like a milestone, I have given so much to Folia, maybe it is time to leave it to the community to continue completing my original intention. This project has been maintained for 6 months and is as old as Folia.
> 
> **Maybe it’s not a good idea to win over users in other people’s projects**

锕抱歉()

**Comment by 347180440** [comment]
![image](https://github.com/killerprojecte/Folia/assets/107541071/c2a9fe8b-4b52-4223-a4f8-2fd66c963f0e)
Current four-hour data

**Comment by MrHua269** [comment]
I guess this issue can reproduce by creating many tick regions,I have seen this issue before

**Comment by MrHua269** [comment]
![image](https://github.com/killerprojecte/Folia/assets/79621885/71a97317-f4de-46a7-b5c0-01417329c708)
I think it's the problem here

**Comment by killerprojecte** [comment]
I will change to a more optimized solution to automatically recycle the cache when the area is not called for a long time.

**Comment by MrHua269** [comment]
> I will change to a more optimized solution to automatically recycle the cache when the area is not called for a long time.

I think you can save all created worlddata in folia because it won't be removed,You can find the method called getOrCreateRegionizedData in class TickRegions

**Comment by 347180440** [comment]
![image](https://github.com/killerprojecte/Folia/assets/107541071/9b91b747-54ee-4390-bac2-074f67a89fdd)
![image](https://github.com/killerprojecte/Folia/assets/107541071/422e4c42-7c98-4251-a920-04529f4eccda)

**Comment by killerprojecte** [comment]
> ![image](https://user-images.githubusercontent.com/107541071/270155878-9b91b747-54ee-4390-bac2-074f67a89fdd.png) ![image](https://user-images.githubusercontent.com/107541071/270155896-422e4c42-7c98-4251-a920-04529f4eccda.png)

Please test the latest version.

**Comment by 347180440** [comment]
Let me observe for a few days.

**Comment by 347180440** [comment]
Time of export: | Friday, October 6, 2023 12:51:02 AM CST
JVM time: | 4h:34m    31.8 GB  player 18-30
![POJY1@Q6L2QBYW} (0XMW~U](https://github.com/killerprojecte/Folia/assets/107541071/20d7d5db-f971-4106-a648-c30149a966e0)
![(F7377)WI_2L_95E$X)4W(J](https://github.com/killerprojecte/Folia/assets/107541071/6e4b032f-f32f-491a-ada0-f9bd16b69ce8)

**Comment by killerprojecte** [comment]
Try reducing the memory allocation to 16G

**Comment by 347180440** [comment]
java -Xmx16G -Dfolia.force-load-all-plugins=true -XX:+HeapDumpOnOutOfMemoryError -jar  folia-paperclip-1.20.1-R0.1-SNAPSHOT-reobf.jar nogui
0 I add a - XX to the startup: + HeapDumpOnOutOfMemoryError
The java_pid15056.hprof file 23.6GB appeared at 20:24 PM on October 07
![image](https://github.com/killerprojecte/Folia/assets/107541071/f8320530-9efa-445b-9d6f-74d75efc0109)

**Comment by 347180440** [comment]
![image](https://github.com/killerprojecte/Folia/assets/107541071/c8db2cf1-c34f-437b-ac80-4d5e638e24cb)
![image](https://github.com/killerprojecte/Folia/assets/107541071/5bea36e6-f359-4dee-8848-2234ffead7af)

**Comment by 347180440** [comment]
I'm uploading this file right now
You can download it directly
If the gameplay download is that I haven't finished uploading
http://zip100.03184.com:10002/my84_20230413_2031/java_pid15056.hprof

**Comment by 347180440** [comment]
I'm uploading this file right now
You can download it directly
If I can't download it, I haven't finished uploading it yet
http://zip100.03184.com:10002/my84_20230413_2031/java_pid15056.hprof

**Comment by 347180440** [comment]
And this is just the memory overflow
Eight or four people hung up last night, and it's overflowing
Hopefully, these tests will give you some useful information
![W6~)BSL2KD86VSFXL@%~@HP](https://github.com/killerprojecte/Folia/assets/107541071/da6aedb0-2fcb-4652-bc9c-f0060d16e27e)
![DZO2Q2`KMBHN(}@HX74@$7C](https://github.com/killerprojecte/Folia/assets/107541071/ef90b063-2a9e-42d5-bba6-4c4db4da3cae)
![K1YHU4A9J}~ML% 1O1D@(9W](https://github.com/killerprojecte/Folia/assets/107541071/e6c959f6-1e4f-42ad-bc28-b9a3f632c732)
![V(6H4)M0ST6{YTCW$RUNPAX](https://github.com/killerprojecte/Folia/assets/107541071/90df08b4-6e6c-43d9-a0a0-f863bbab59a3)
![R63E3`1)7_)$7AC}$S5S71A](https://github.com/killerprojecte/Folia/assets/107541071/3f35bc53-50ca-491d-9917-687be7b2b849)
![N{IA }RQ NEG2LR~%0F~${A](https://github.com/killerprojecte/Folia/assets/107541071/315abab6-bfeb-4c9a-84d5-0c68f00c5629)

**Comment by 347180440** [comment]
And, this was a recent RAM overflow.
Last night, there were 8 to 4 players AFK, with a total duration of 8 hours. The setting is still -Xmx16G.
I hope these tests can be helpful to you.
![W6~)BSL2KD86VSFXL@%~@HP](https://github.com/killerprojecte/Folia/assets/107541071/dbb859e5-128d-44e7-8548-aa4d73094d8e)
![DZO2Q2`KMBHN(}@HX74@$7C](https://github.com/killerprojecte/Folia/assets/107541071/deb31886-b55f-4d8f-8af6-a2c07f5ef117)
![K1YHU4A9J}~ML% 1O1D@(9W](https://github.com/killerprojecte/Folia/assets/107541071/fdd51aff-677a-47d3-a07a-f9de7ac914ed)
![V(6H4)M0ST6{YTCW$RUNPAX](https://github.com/killerprojecte/Folia/assets/107541071/9d19b773-3230-43ec-9120-ed4324f92c1a)
![R63E3`1)7_)$7AC}$S5S71A](https://github.com/killerprojecte/Folia/assets/107541071/82679600-6a02-4661-97d6-58e38588b468)
![N{IA }RQ NEG2LR~%0F~${A](https://github.com/killerprojecte/Folia/assets/107541071/b02c233c-838f-414a-ae65-2bfe53536545)

**Comment by 347180440** [comment]
![DZO2Q2`KMBHN(}@HX74@$7C](https://github.com/killerprojecte/Folia/assets/107541071/0bf93d9e-90bb-4158-a628-a826bd670925)

**Comment by killerprojecte** [comment]
Thanks, I will check this dump carefully. I think your startup script can try to be optimized. Try aikar's JVM Flags or follow Folia's GC Setting to configure it.
