### ISSUE TITLE
The aggro distance between an (Endermite) and an (Enderman) is only about 10 blocks.

### ISSUE THREAD

**Issue by 347180440** [killerprojecte/Folia#14]
### Expected behavior

The official Folia core's hostility is normal; it has been confirmed that the issue only occurs with DirtyFolia.

### Observed/Actual behavior

unll

### Steps/models to reproduce

unll

### Plugin and Datapack List

unll

### Folia version

> version
[01:54:35 INFO]: Checking version, please wait...
[01:54:36 INFO]: This server is running DirtyFolia version git-DirtyFolia-"c7ded42" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: c7ded42 on ver/1.20)
You are running the latest version
Previous version: git-Purpur-2022 (MC: 1.20.1)

**Comment by killerprojecte** [comment]
I don't think DirtyFolia causes these problems. DirtyFolia does not modify any entity pathfinding content.

**Comment by killerprojecte** [comment]
If it is really caused by DirtyFolia, I cannot solve the problem. This should be a side effect of the modification of the thread scheduling mechanism.

**Comment by MrHua269** [comment]
It maybe a bug in paper,And it get fixed at 517f8fbbac2467fb24fa87d6bd56ce5c1b9bc972
