### ISSUE TITLE
Kaiiju

### ISSUE THREAD

**Issue by xKumorio** [killerprojecte/Folia#4]
### Expected behavior

Can you take all the patches from kaiiju and update folia for the kaiiju branch?

### Observed/Actual behavior

Can you take all the patches from kaiiju and update folia for the kaiiju branch?

### Steps/models to reproduce

Can you take all the patches from kaiiju and update folia for the kaiiju branch?

### Plugin and Datapack List

Can you take all the patches from kaiiju and update folia for the kaiiju branch?

### Folia version

Can you take all the patches from kaiiju and update folia for the kaiiju branch?

### Other

Can you take all the patches from kaiiju and update folia for the kaiiju branch?

**Comment by killerprojecte** [comment]
Attention!
Upstream updates of the Kaiiju experimental branch are not prioritized for support.
I will sync upstream only when I have time
