### ISSUE TITLE
folia.force-load-all-plugins where

### ISSUE THREAD

**Issue by IamRymatics** [killerprojecte/Folia#7]
### Expected behavior

why can't I see folia.force-load-all-plugins

### Observed/Actual behavior

why can't I see folia.force-load-all-plugins

### Steps/models to reproduce

why can't I see folia.force-load-all-plugins

### Plugin and Datapack List

no plugins

### Folia version

1.20.1

**Comment by Posussy** [comment]
i have the same issue i dont know where i activate the folia.force-load-all-plugins

**Comment by 347180440** [comment]
+1

**Comment by upchui** [comment]
I was wondering about the same thing too and found nothing. That's why I opened the .jar file of the plugin and wrote 'folia-supported: true' at the bottom of the plugin.yml file. Then, I put the file back into the plugin .jar file.

**Comment by killerprojecte** [comment]
in your jvm parameters

**Comment by killerprojecte** [comment]
Like "java -Dfolia.force-load-all-plugins=true -jar folia-xxxx.jar --nogui"

**Comment by killerprojecte** [comment]
issue has been resolved
